[package]
name = "project-stash"
version = "0.1.0"
description = "Personal budget tracker"
authors = []
edition = "2021"

[lib]
name = "project_stash_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "project-stash"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
